version: "3.8"
services:
  library:
    build: ./library/
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    env_file:
      - .env
  counter:
    build: ./counter/
    restart: always
    expose:
      - "3000"
    volumes:
      - ./counter/db.json:/counter/db.json
    depends_on:
      - library